name: cache node modules

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
    outputs:
      cache-hit:
        description: "Whether cache was hit"
        value: ${{ jobs.cache-node.outputs.cache-hit }}

jobs:
  cache-node:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
