name:  live director ci/cd Pipeline
on:
    push:
        branches: [ "main" ]
        paths-ignore:
            -   'README.md'
            -   'helm/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout source
            uses: actions/checkout@v4
        -   name: load & cach dependencies
            uses: ./.github/actions/cach_deps
            with:
                caching: false
        -   name: Build
            run: npm run build
        -   name: Test
            run: npm test
    
    code-qualities:
        runs-on: ubuntu-latest
        needs: build
        steps:
        -   name: checkout source
            uses: actions/checkout@v4
        -   name: load & cach dependencies
            uses: ./.github/actions/cach_deps
        -   name: Run lint
            run: npm run lint
    
    push:
        runs-on: ubuntu-latest
        needs: code-qualities
        environment: staging
        steps:
        -   name: checkout source
            uses: actions/checkout@v4
        -   name: Set up Docker buildx
            uses: docker/setup-buildx-action@v3
        -   name: Login to DockerHub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -   name: Build and Push action
            uses: docker/build-push-action@v6
            with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/live_dir:${{ github.run_id }}

    update-helm-chart:
        runs-on: ubuntu-latest
        needs: push
        steps:
            -   name: Chekout source
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.TOKEN }}
            -   name: Update tag in Helm chart
                run: |
                    sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/live-dir-chart/values.yaml

            -   name: Commit and push changes
                run: |
                    git config --global user.email "tashitakuley@gmail.com"
                    git config --global user.name "Taship1"
                    git add helm/live-dir-chart/values.yaml
                    git commit -m "Update tag in Helm chart"
                    git push
        